// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc9n1gzUGGzhqoA-x_fMp5MYulDh0yj2g',
    appId: '1:737977511006:web:9192ed736a30bb01d258cf',
    messagingSenderId: '737977511006',
    projectId: 'truckcab-76a46',
    authDomain: 'truckcab-76a46.firebaseapp.com',
    storageBucket: 'truckcab-76a46.firebasestorage.app',
    measurementId: 'G-QYYECBCHC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO-eUVb85W8XX7u1_MogbO0s_IZ9VA4hg',
    appId: '1:737977511006:android:dffe210164ef9e0dd258cf',
    messagingSenderId: '737977511006',
    projectId: 'truckcab-76a46',
    storageBucket: 'truckcab-76a46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpu02SkXKtDe4ZNHFkmE3E5_aO6d9jqKk',
    appId: '1:737977511006:ios:3793ae87b1ed66abd258cf',
    messagingSenderId: '737977511006',
    projectId: 'truckcab-76a46',
    storageBucket: 'truckcab-76a46.firebasestorage.app',
    iosBundleId: 'com.example.truckcab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpu02SkXKtDe4ZNHFkmE3E5_aO6d9jqKk',
    appId: '1:737977511006:ios:3793ae87b1ed66abd258cf',
    messagingSenderId: '737977511006',
    projectId: 'truckcab-76a46',
    storageBucket: 'truckcab-76a46.firebasestorage.app',
    iosBundleId: 'com.example.truckcab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc9n1gzUGGzhqoA-x_fMp5MYulDh0yj2g',
    appId: '1:737977511006:web:a310088bba17e521d258cf',
    messagingSenderId: '737977511006',
    projectId: 'truckcab-76a46',
    authDomain: 'truckcab-76a46.firebaseapp.com',
    storageBucket: 'truckcab-76a46.firebasestorage.app',
    measurementId: 'G-7PX63TF1ND',
  );

}